
[analytics]
enabled = {{ if .Values.gateway.moesifKey }}true{{ else }}false{{ end }}
allow_payloads = false
enabled_publishers = ["moesif"]

[analytics.publishers.moesif]
application_id = "{{ .Values.gateway.moesifKey }}"

[router]
gateway_host = "*"

[router.access_logs]
enabled = true

[controller.server]
gateway_id = "{{ .Values.gateway.gatewayId }}"

[controller.controlplane]
insecure_skip_verify = true

[controller.auth.basic]
enabled = true

[[controller.auth.basic.users]]
username = "admin"
password = "admin"
roles = ["admin"]

[policy_configurations.llm_cost_v1]
pricing_file = "/etc/policy-engine/llm-pricing/model_prices.json"
