SET IDENTITY_INSERT AM_ALERT_TYPES ON;
GO
INSERT INTO AM_ALERT_TYPES (ALERT_TYPE_ID, ALERT_TYPE_NAME, STAKE_HOLDER)
VALUES (998, 'test-dc2-replication', 'admin-dashboard');
GO
SET IDENTITY_INSERT AM_ALERT_TYPES OFF;
GO
