apiVersion: v1
kind: Service
metadata:
  name: {{ include "wso2am-mysql.fullname" . }}
  labels:
    {{- include "wso2am-mysql.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "wso2am-mysql.selectorLabels" . | nindent 4 }}
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
