CREATE DATABASE apim_db;
GO
CREATE DATABASE shared_db;
GO

-- Enable snapshot isolation (recommended by WSO2 APIM to avoid deadlocks)
ALTER DATABASE apim_db SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE apim_db SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE shared_db SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE shared_db SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
GO
