replicaCount: 1

image:
  repository: isurugunarathne/webhook-orders
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

env:
  hubUrl: ""

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"
