apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wso2am-postgresql.fullname" . }}
  labels:
    {{- include "wso2am-postgresql.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wso2am-postgresql.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "wso2am-postgresql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          args: ["-c", "max_connections=300"]
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgresql
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: postgresql-data
          {{- if .Values.postgresql.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "wso2am-postgresql.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: initdb
          configMap:
            name: {{ include "wso2am-postgresql.fullname" . }}-initdb
            defaultMode: 0755
