apiVersion: v1
kind: Service
metadata:
  name: {{ include "wso2am-postgresql.fullname" . }}
  labels:
    {{- include "wso2am-postgresql.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "wso2am-postgresql.selectorLabels" . | nindent 4 }}
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
