apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-gw.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-gw.labels" . | nindent 4 }}
type: Opaque
stringData:
  APIP_GW_GATEWAY_REGISTRATION_TOKEN: {{ .Values.gateway.registrationToken | quote }}
  MOESIF_KEY: {{ .Values.gateway.moesifKey | quote }}
