apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-gw.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-gw.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "platform-gw.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: rest-api
      port: 9090
      targetPort: 9090
      protocol: TCP
    - name: admin
      port: 9092
      targetPort: 9092
      protocol: TCP
